self-hosted-runner:
  # Labels of self-hosted runner in array of strings.
  labels:
    - "ubuntu-24.04-arm"
    - "ubuntu-22.04-arm"
    - "macos-15-intel"
# Configuration variables in array of strings defined in your repository or
# organization. `null` means disabling configuration variables check.
# Empty array means no configuration variable is allowed.
config-variables: null
